### Iniciar Viagem
POST http://localhost:8080/api/diario/start/5514981864662
Content-Type: application/json

{
  "odometroValue": 12345
}

### Abastecer
POST http://localhost:8080/api/diario/abastecimento/5514981864662
Content-Type: application/json

{
  "litros": 50
}

### Get Motorista
GET http://localhost:8080/api/driver/5514981864662
Content-Type: application/json

### Listar Motoristas
GET http://localhost:8080/api/driver/list
Content-Type: application/json

### Cadastro Motorista
POST http://localhost:8080/api/driver/register
Content-Type: application/json

{
  "name": "Lucas Jozefovicz",
  "phoneNumber": "5514981864662"
}

### Atualizar Cadastro Motorista
PUT http://localhost:8080/api/driver/update/14981864662
Content-Type: application/json

{
  "name": "Lucas Silva",
  "phoneNumber": "5511981864662"
}

### Deletar Cadastro Motorista
DELETE http://localhost:8080/api/driver/delete/14981864662
###