
### Listar Motoristas
GET http://botservice-env.eba-wcc37xpj.us-east-2.elasticbeanstalk.com/api/driver/list
Content-Type: application/json

### Cadastro Motorista
POST http://localhost:8080/api/driver/register
Content-Type: application/json

{
  "name": "Lucass",
  "phoneNumber": "5514981864662"
}

### Atualizar Cadastro Motorista
PUT http://localhost:8080/api/driver/update/14981864662
Content-Type: application/json

{
  "name": "Lucas Silva",
  "phoneNumber": "5511981864662"
}

### Deletar Cadastro Motorista
DELETE http://localhost:8080/api/driver/delete/14981864662
###